# Form implementation generated from reading ui file 'src/gui/logs.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Logs(object):
    def setupUi(self, Logs):
        # Logs.setObjectName("Logs")
        # Logs.resize(317, 270)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Logs)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Logs)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 297, 250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(-10, 1, 301, 241))
        self.listWidget.setMinimumSize(QtCore.QSize(281, 221))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Logs)
        QtCore.QMetaObject.connectSlotsByName(Logs)

    def retranslateUi(self, Logs):
        _translate = QtCore.QCoreApplication.translate
        Logs.setWindowTitle(_translate("Logs", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Logs = QtWidgets.QWidget()
    ui = Ui_Logs()
    ui.setupUi(Logs)
    Logs.show()
    sys.exit(app.exec())
