# Form implementation generated from reading ui file 'src/gui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 533)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditFilePath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditFilePath.setObjectName("lineEditFilePath")
        self.horizontalLayout.addWidget(self.lineEditFilePath)
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConfirm.setDefault(False)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout.addWidget(self.pushButtonConfirm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxLanguage = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxLanguage.setEditable(False)
        self.comboBoxLanguage.setCurrentText("")
        self.comboBoxLanguage.setObjectName("comboBoxLanguage")
        self.horizontalLayout_2.addWidget(self.comboBoxLanguage)
        self.comboBoxLoggingLevel = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxLoggingLevel.setObjectName("comboBoxLoggingLevel")
        self.horizontalLayout_2.addWidget(self.comboBoxLoggingLevel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GCode Optimizer"))
        self.pushButtonConfirm.setText(_translate("MainWindow", "Confirm"))
        self.comboBoxLanguage.setPlaceholderText(_translate("MainWindow", "Language..."))
        self.comboBoxLoggingLevel.setPlaceholderText(_translate("MainWindow", "Logging level..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
